package utils;

import java.util.ArrayList;

public class ICSTimeSlotStack extends ArrayList<ICSTimeSlot> {
	
	private static final long serialVersionUID = 3606713725038303452L;

	public ICSTimeSlotStack() {
		super();
	}
	
	//Generated by Copilot
	public ICSTimeSlot searchByStart(String looked) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEnd(String looked) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByCours(String looked) {
		for(ICSTimeSlot slot : this) {
			if(slot.getCours().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchBySalle(String looked) {
		for(ICSTimeSlot slot : this) {
			if(slot.getSalle().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByProfesseur(String looked) {
		for(ICSTimeSlot slot : this) {
			if(slot.getProfesseur().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndEnd(String lookedStart, String lookedEnd) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndCours(String lookedStart, String lookedCours) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndSalle(String lookedStart, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndProfesseur(String lookedStart, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEndAndCours(String lookedEnd, String lookedCours) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEndAndSalle(String lookedEnd, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEndAndProfesseur(String lookedEnd, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByCoursAndSalle(String lookedCours, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByCoursAndProfesseur(String lookedCours, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchBySalleAndProfesseur(String lookedSalle, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getSalle().equals(lookedSalle) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndEndAndCours(String lookedStart, String lookedEnd, String lookedCours) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndEndAndSalle(String lookedStart, String lookedEnd, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndEndAndProfesseur(String lookedStart, String lookedEnd, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndCoursAndSalle(String lookedStart, String lookedCours, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndCoursAndProfesseur(String lookedStart, String lookedCours, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByStartAndSalleAndProfesseur(String lookedStart, String lookedSalle, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getSalle().equals(lookedSalle) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEndAndCoursAndSalle(String lookedEnd, String lookedCours, String lookedSalle) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public ICSTimeSlot searchByEndAndCoursAndProfesseur(String lookedEnd, String lookedCours, String lookedProfesseur) {
		for(ICSTimeSlot slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}



}
