package utils;

import java.time.LocalDateTime;
import java.util.ArrayList;

import modele.Cours;

public class ListeCours extends ArrayList<Cours> {
	
	private static final long serialVersionUID = 3606713725038303452L;

	public ListeCours() {
		super();
	}
	
	//Generated by Copilot
	public Cours searchByStart(LocalDateTime looked) {
		for(Cours slot : this) {
			if(slot.getStart().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEnd(LocalDateTime looked) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByCours(String looked) {
		for(Cours slot : this) {
			if(slot.getCours().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchBySalle(String looked) {
		for(Cours slot : this) {
			if(slot.getSalle().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByProfesseur(String looked) {
		for(Cours slot : this) {
			if(slot.getProfesseur().equals(looked)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndEnd(LocalDateTime lookedStart, String LocalDateTime) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndCours(LocalDateTime lookedStart, String lookedCours) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndSalle(LocalDateTime lookedStart, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndProfesseur(LocalDateTime lookedStart, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEndAndCours(LocalDateTime lookedEnd, String lookedCours) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEndAndSalle(LocalDateTime lookedEnd, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEndAndProfesseur(LocalDateTime lookedEnd, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByCoursAndSalle(String lookedCours, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByCoursAndProfesseur(String lookedCours, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchBySalleAndProfesseur(String lookedSalle, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getSalle().equals(lookedSalle) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndEndAndCours(LocalDateTime lookedStart, LocalDateTime lookedEnd, String lookedCours) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndEndAndSalle(LocalDateTime lookedStart, LocalDateTime lookedEnd, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndEndAndProfesseur(LocalDateTime lookedStart, LocalDateTime lookedEnd, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getEnd().equals(lookedEnd) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndCoursAndSalle(LocalDateTime lookedStart, String lookedCours, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndCoursAndProfesseur(LocalDateTime lookedStart, String lookedCours, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByStartAndSalleAndProfesseur(LocalDateTime lookedStart, String lookedSalle, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getStart().equals(lookedStart) && slot.getSalle().equals(lookedSalle) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEndAndCoursAndSalle(LocalDateTime lookedEnd, String lookedCours, String lookedSalle) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours) && slot.getSalle().equals(lookedSalle)) {
				return slot;
			}
		}
		return null;
	}

	//Generated by Copilot
	public Cours searchByEndAndCoursAndProfesseur(LocalDateTime lookedEnd, String lookedCours, String lookedProfesseur) {
		for(Cours slot : this) {
			if(slot.getEnd().equals(lookedEnd) && slot.getCours().equals(lookedCours) && slot.getProfesseur().equals(lookedProfesseur)) {
				return slot;
			}
		}
		return null;
	}
	
	public Cours searchCoursBetweenStartAndEnd(LocalDateTime lookedStart, LocalDateTime lookedEnd) {
		for(Cours slot : this) {
			if(slot.getStart().isAfter(lookedStart) && slot.getEnd().isBefore(lookedEnd)) {
				return slot;
			}
		}
		return null;
	}



}
